.TH YAD-TOOLS "1" "April 2021" "yad-tools" "User Commands"

.SH NAME
yad-tools \- show some miscellaneous stuff.

.SH SYNOPSIS
.B yad-tools
.RI [OPTIONS]
.RI STRING

.SH DESCRIPTION
\fByad-tools\fR is a small command-line utility for getting information that may be usefull in scripts.

.SH OPTIONS

.SS General options
.TP
\fB\-f\fR, \fB\-\-pfd\fR
This mode is intended to transform font names from pango to xft specification and vice versa.
Additional argument is font name.
.TP
\fB\-i\fR, \fB\-\-icon\fR
This mode is intended to get full path to icon file from icon name.
Additional argument is icon name.
.TP
\fB\-c\fR, \fB\-\-color\fR
This mode is intended for works with colors.
.TP
.B \-\-show-langs
Show list of available languages for spell checking. Works only if yad built with \fIGSpell\fP support.
.TP
.B \-\-show-themes
Show list of available GtkSourceView themes. Works only if yad built with \fIGtkSourceView\fP support.

.SS PFD mode options
.TP
\fB\-x\fR, \fB\-\-xft\fR
Print font name in xft format. This is default.
.TP
\fB\-p\fR, \fB\-\-pango\fR
Print font name in pango format.

.SS Icon mode options
.TP
\fB\-s\fR, \fB\-\-size\fR=\fISIZE\fP
Use specified icon size. Default is 24.
.TP
\fB\-t\fR, \fB\-\-type\fR=\fITYPE\fP
Obtain icon size from one of predefined GTK+ types. \fITYPE\fP is one of the following \fImenu\fP, \fIbutton\fP, \fIsmall_toolbar\fP, \fIlarge_toolbar\fP, \fIdnd\fP or \fIdialog\fP,
.TP
\fB\-m\fR, \fB\-\-mime\fP
Get generic icon name for specified mime type.
.TP
\fB\-\-theme\fR=\fITHEME\fP
Use specified icon theme instead of default.

.SS Color mode options
.TP
\fB\-\-pick\fP
Pick up screen color.
