.TH PFD "1" "February 2019" "pfd" "User Commands"
.SH NAME
pfd \- convert font description between xft and pango formats
.SH SYNOPSIS
.B pfd
.RI [ OPTIONS ] 
.RI FONT
.SH DESCRIPTION
\fBpfd\fR is a small command-line utility to transform font names from pango to xft specification and vice versa.
.SH OPTIONS
.TP
\fB\-x\fR, \fB\-\-xft\fR
Print font name in xft format. This is default.
.TP
\fB\-p\fR, \fB\-\-pango\fR
Print font name in pango format.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print current version.
